site_name: OSLLM.ai
site_url: https://docs.osllm.ai

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - toc.integrate
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: indoxArcg/assets/logo.png  # Updated path
extra_css:
  - indoxArcg/assets/custom.css  # Updated path

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
      baselevel: 1
      separator: "_"
      title: On this page
      permalink_title: Anchor link to this section for reference
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Indox:
      - Overview: indoxArcg/index.md
      - Data Connectors:
          - Overview: indoxArcg/data_connectors/README.md
          - Document: indoxArcg/data_connectors/document.md
          - Academic Connectors: indoxArcg/data_connectors/Academic-Connectors.md
          - Development Connectors: indoxArcg/data_connectors/Development-Connectors.md
          - Google Connectors: indoxArcg/data_connectors/Google-Connectors.md
          - Multimedia Connectors: indoxArcg/data_connectors/Multimedia-Connectors.md
          - Social Connectors: indoxArcg/data_connectors/Social-Connectors.md
      - Data Loader:
          - Overview: indoxArcg/data_loader/README.md
          - Office Loaders: indoxArcg/data_loader/Office-Loaders.md
          - PDF Loaders: indoxArcg/data_loader/PDF-Loaders.md
          - Scientific Loaders: indoxArcg/data_loader/Scientific-Loaders.md
          - Structured Data Loaders: indoxArcg/data_loader/Structured-Data-Loaders.md
          - Web Loaders: indoxArcg/data_loader/Web-Loaders.md
          - Text Loaders: indoxArcg/data_loader/text-Loaders.md
      - Splitters:
          - Overview: indoxArcg/splitters/README.md
          - AI21 Semantic Splitter: indoxArcg/splitters/AI21semantic_splitter.md
          - Character Splitter: indoxArcg/splitters/Charachter_splitter.md
          - Markdown Text Splitter: indoxArcg/splitters/Markdown_text_splitter.md
          - Recursively Splitter: indoxArcg/splitters/Recursively_splitter.md
          - Semantic Splitter: indoxArcg/splitters/Semantic_splitter.md
      - Data Loader and Splitter:
          - Overview: indoxArcg/data_loader_and_splitter/README.md
          - Unstructured Load and Split: indoxArcg/data_loader_and_splitter/unstructured_load_and_split.md
          - Clustered Split: indoxArcg/data_loader_and_splitter/clustered_split.md
          - Simple Load Split: indoxArcg/data_loader_and_splitter/simple_load_split.md
      - Vectorstores:
          - Overview: indoxArcg/vectorstores/index.md
          - General Purpose Databases: indoxArcg/vectorstores/general-purpose-databases.md
          - General Purpose Vector Databases: indoxArcg/vectorstores/general-purpose-vector-databases.md
          - Graph Databases: indoxArcg/vectorstores/graph-databases.md
          - Purpose Built Vector Databases: indoxArcg/vectorstores/purpose-built-vector-databases.md
          - Embedded Libraries: indoxArcg/vectorstores/embedded-libraries.md
      - Pipelines:
          - CAG: indoxArcg/pipelines/cag.md
          - RAG: indoxArcg/pipelines/rag.md
      - Graphs:
          - Memgraph: indoxArcg/graphs/memgraph.md
          - Neo4j: indoxArcg/graphs/neo4jgraph.md
      - Tools:
          - MultiQuery: indoxArcg/tools/multiquery.md
          - MultiVector: indoxArcg/tools/multivector.md
      - Embedding Models: indoxArcg/embedding_models.md
      - LLMs: indoxArcg/llms.md
      - Quick Start: indoxArcg/quick_start.md
  - IndoxJudge:
      - Overview:
          - Architecture: indoxJudge/overview/architecture.md
          - Introduction: indoxJudge/overview/introduction.md
      - Metrics:
          - Bias and Fairness:
              - Bias: indoxJudge/metrics/bias-fairness/Bias.md
              - Fairness: indoxJudge/metrics/bias-fairness/Fairness.md
              - Stereotype and Bias: indoxJudge/metrics/bias-fairness/Stereotype-and-Bias.md
          - NLP Metrics:
              - Basic: indoxJudge/metrics/nlp-metrics/basic.md
              - Advanced: indoxJudge/metrics/nlp-metrics/advanced.md
          - Quality and Accuracy:
              - Faithfulness: indoxJudge/metrics/quality-accuracy/Faithfulness.md
              - Hallucination: indoxJudge/metrics/quality-accuracy/Hallucination.md
              - Knowledge Retention: indoxJudge/metrics/quality-accuracy/KnowledgeRetention.md
              - Misinformation: indoxJudge/metrics/quality-accuracy/Misinformation.md
          - Relevancy and Context:
              - Answer Relevancy: indoxJudge/metrics/relevancy-context/AnswerRelevancy.md
              - Contextual Relevancy: indoxJudge/metrics/relevancy-context/ContextualRelevancy.md
          - Robustness:
              - Adversarial Robustness: indoxJudge/metrics/robustness/AdversarialRobustness.md
              - Out of Distribution Robustness: indoxJudge/metrics/robustness/OutOfDistributionRobustness.md
              - Robustness to Adversarial Demonstrations: indoxJudge/metrics/robustness/RobustnesstoAdversarialDemonstrations.md
          - Safety and Ethics:
              - Harmfulness: indoxJudge/metrics/safety-ethics/Harmfulness.md
              - Machine Ethics: indoxJudge/metrics/safety-ethics/MachineEthics.md
              - Privacy: indoxJudge/metrics/safety-ethics/Privacy.md
              - Safety Toxicity: indoxJudge/metrics/safety-ethics/SafetyToxicity.md
              - Toxicity: indoxJudge/metrics/safety-ethics/Toxicity.md
              - Toxicity Discriminative: indoxJudge/metrics/safety-ethics/ToxicityDiscriminative.md
          - Summary Metrics:
              - Conciseness: indoxJudge/metrics/summary-metrics/Conciseness.md
              - Factual Consistency: indoxJudge/metrics/summary-metrics/FactualConsistency.md
              - Information Coverage: indoxJudge/metrics/summary-metrics/InformationCoverage.md
              - Relevance: indoxJudge/metrics/summary-metrics/Relevance.md
              - Structure Quality: indoxJudge/metrics/summary-metrics/StructureQuality.md
      - Pipelines:
          - Overview: indoxJudge/pipelines/README.md
          - Evaluator: indoxJudge/pipelines/Evaluator.md
          - LLM Evaluator: indoxJudge/pipelines/LLMEvaluator.md
          - RAG Evaluator: indoxJudge/pipelines/RagEvaluator.md
          - Safety Evaluator: indoxJudge/pipelines/SafetyEvaluator.md
          - Evaluation Analyzer: indoxJudge/pipelines/EvaluationAnalyzer.md
  - IndoxGen:
      - Generative Data Synth: indoxGen/GenerativeDataSynth.md
      - Hybrid GAN + LLM: indoxGen/HybridGAN+LLM.md
      - Interactive Feedback Synth: indoxGen/InteractiveFeedbackSynth.md
      - Prompt Based Synth: indoxGen/PromptBasedSynth.md
      - Attribute Prompt Synth: indoxGen/AttributePromptSynth.md
      - Few Shot Prompt Synth: indoxGen/FewShotPromptSynth.md
      - GAN Torch Tensor: indoxGen/GAN-Torch-Tensor.md
      - License: indoxGen/LICENSE.md
  - IndoxMiner:
      - Classification:
          - Overview: indoxMiner/classification/Classification_module.md
          - AltCLIP: indoxMiner/classification/altclip.md
          - BioCLIP: indoxMiner/classification/bioclip.md
          - MetaCLIP: indoxMiner/classification/metaclip.md
          - MobileCLIP: indoxMiner/classification/MobileCLIP.md
          - RemoteCLIP: indoxMiner/classification/RemoteCLIP.md
          - SigCLIP: indoxMiner/classification/sigclip.md
          - ViT: indoxMiner/classification/vit.md
      - Detection:
          - Contributing: indoxMiner/detection/CONTRIBUTING.md
          - Object Detection: indoxMiner/detection/object_detection_with_indoxMiner.md
      - Extraction:
          - Automatic Schema Detection: indoxMiner/extraction/Automatic Schema Detection.md
          - Document Type Support: indoxMiner/extraction/Document Type Support.md
          - Extracting Structured Data: indoxMiner/extraction/Extracting Structured Data from Images.md
          - LLM Support: indoxMiner/extraction/LLM Support in Indox Miner.md
          - Output Types: indoxMiner/extraction/Output Types in Indox Miner.md
          - Predefined Schema Support: indoxMiner/extraction/Predefined Schema Support in Indox Miner.md
      - Multimodals:
          - Multimodal Models: indoxMiner/multimodals/multimodal_models_with_indoxminer.md
  - About:
      - License: license.md
