name: Check FTP Status

on:
  workflow_dispatch:  # Manually trigger this workflow

jobs:
  test_ftp:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Check FTP Connection
        run: |
          if curl --ftp-pasv -u "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
                  ftp://${{ secrets.FTP_SERVER }}/ --silent --fail; then
            echo "✅ FTP connection successful!"
          else
            echo "❌ FTP connection failed!"
            exit 1
          fi
